package org.example.rpcprotocol;

public enum ResponseType {
    OK,
    ERROR,
    GENERATE_RANDOM_CONFIGURATION_RESPONSE,
    UPDATE,
    ADD_CLASAMENT_RESPONSE,
    GET_CLASAMENTE_RESPONSE,
    GET_POINTS_RESPONSE,
    GENERATE_RANDOM_LETTER_RESPONSE,
    GET_POINTS_FOR_CHOSEN_LETTER_RESPONSE
}
